name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  # Job to run change detection
  changes:
    runs-on: ubuntu-latest
    outputs:
      # Expose matched filters as job 'images' output variable
      images: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          # Use context to get the branch where commits were pushed.
          # If there is only one long-lived branch (e.g. master),
          # you can specify it directly.
          # If it's not configured, the repository default branch is used.
          base: ${{ github.ref }}
          filters: |
            acme/certbot: 'acme/certbot/**'
            acme/certbot-dns-cloudflare: 'acme/certbot-dns-cloudflare/**'
            acme/lego: 'acme/lego/**'
            aws-cli: 'aws-cli/**'
            black: 'black/**'
            buildpack-deps/ubuntu/focal/curl: 'buildpack-deps/ubuntu/focal/curl/**'
            buildpack-deps/ubuntu/focal/scm: 'buildpack-deps/ubuntu/focal/scm/**'
            buildpack-deps/ubuntu/focal: 'buildpack-deps/ubuntu/focal/*'
            buildpack-deps/ubuntu/jammy/curl: 'buildpack-deps/ubuntu/jammy/curl/**'
            buildpack-deps/ubuntu/jammy/scm: 'buildpack-deps/ubuntu/jammy/scm/**'
            buildpack-deps/ubuntu/jammy: 'buildpack-deps/ubuntu/jammy/**'
            cinc/cinc-workstation: 'cinc/cinc-workstation/**'
            doctl: 'doctl/**'
            dokken/almalinux-8: 'dokken/almalinux-8/**'
            dokken/almalinux-9: 'dokken/almalinux-9/**'
            dokken/amazonlinux-2: 'dokken/amazonlinux-2/**'
            dokken/amazonlinux-2023: 'dokken/amazonlinux-2023/**'
            dokken/centos-stream-8: 'dokken/centos-stream-8/**'
            dokken/centos-stream-9: 'dokken/centos-stream-9/**'
            dokken/debian-11: 'dokken/debian-11/**'
            dokken/debian-12: 'dokken/debian-12/**'
            dokken/opensuse-leap-15.3: 'dokken/opensuse-leap-15.3/**'
            dokken/opensuse-leap-15.4: 'dokken/opensuse-leap-15.4/**'
            dokken/oraclelinux-8: 'dokken/oraclelinux-8/**'
            dokken/oraclelinux-9: 'dokken/oraclelinux-9/**'
            dokken/rockylinux-8: 'dokken/rockylinux-8/**'
            dokken/rockylinux-9: 'dokken/rockylinux-9/**'
            dokken/ubuntu-20.04: 'dokken/ubuntu-20.04/**'
            dokken/ubuntu-22.04: 'dokken/ubuntu-22.04/**'
            markdownlint: 'markdownlint/**'
            node/18/jammy: 'node/18/jammy/**'
            prometheus/alertmanager: 'prometheus/alertmanager/**'
            prometheus/blackbox_exporter: 'prometheus/blackbox_exporter/**'
            prometheus/collectd_exporter: 'prometheus/collectd_exporter/**'
            prometheus/node_exporter: 'prometheus/node_exporter/**'
            prometheus/prometheus: 'prometheus/prometheus/**'
            pulumi/pulumi-base: 'pulumi/pulumi-base/**'
            pulumi/pulumi-python: 'pulumi/pulumi-python/**'
            python/3.8/focal: 'python/3.8/focal/**'
            python/3.8/slim-focal: 'python/3.8/slim-focal/**'
            python/3.8/jammy: 'python/3.8/jammy/**'
            python/3.8/slim-jammy: 'python/3.8/slim-jammy/**'
            python/3.9/focal: 'python/3.9/focal/**'
            python/3.9/slim-focal: 'python/3.9/slim-focal/**'
            python/3.9/jammy: 'python/3.9/jammy/**'
            python/3.9/slim-jammy: 'python/3.9/slim-jammy/**'
            ruby/3.1/jammy: 'ruby/3.1/jammy/**'
            ruby/3.1/slim-jammy: 'ruby/3.1/slim-jammy/**'
            ruby/3.2/jammy: 'ruby/3.2/jammy/**'
            ruby/3.2/slim-jammy: 'ruby/3.2/slim-jammy/**'
            shellcheck: 'shellcheck/**'

  # Job to build and test each of the modified images
  build:
    needs: changes
    strategy:
      matrix:
        # Parse JSON array containing names of all filters matching any of changed files
        # e.g. ['image1', 'image2'] if both image folders contains changes
        image: ${{ fromJSON(needs.changes.outputs.images) }}
    if: ${{ needs.changes.outputs.images != '[]' && needs.changes.outputs.images != '' }}
    runs-on: ubuntu-latest
    steps:
      - uses: polymathrobotics/container-build-publish-action@main
        with:
          workdir: ${{ matrix.image }}
          dockerhub-username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
          dockerhub-password: ${{ secrets.CONTAINER_DESCRIPTION_PASSWORD }}
