name: hadolint Merge
# Controls when the action will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths:
    - 'hadolint/**'
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Set job-wide defaults
    defaults:
      run:
        working-directory: hadolint
# Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Fetch from GitHub 
        uses: actions/checkout@v3

      - name: Check the Containerfile with hadolint
        run: |
          $(git rev-parse --show-toplevel)/bin/lint.sh

      - name: Install QEMU static binaries
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Set the tags
        id: tags
        run: |
          echo "tags=$($(git rev-parse --show-toplevel)/bin/list-tags-github-env.sh)" >> $GITHUB_ENV

      - name: Build locally for testing
        uses: docker/build-push-action@v2
        with:
          load: true
          context: hadolint
          file: hadolint/Containerfile
          tags: ${{ env.tags }}

      # No tests right now because this is from scratch

      - name: Set the platforms
        id: platforms
        run: |
          echo "platforms=$($(git rev-parse --show-toplevel)/bin/list-platforms-github-env.sh)" >> $GITHUB_ENV

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          context: hadolint
          file: hadolint/Containerfile
          platforms: ${{env.platforms}}
          tags: ${{env.tags}}

      - name: Update Docker Hub Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINER_DESCRIPTION_PASSWORD }}
          short-description: 'Dockerfile linter, validate inline bash, written in Haskell.'
          repository: 'polymathrobotics/hadolint'
          readme-filepath: hadolint/README.md