name: ros-humble

on:
  push:
    branches: [ main ]
    paths:
      - 'ros/humble/ubuntu/jammy/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'ros/humble/ubuntu/jammy/**'
  workflow_dispatch:
jobs:
  build:
    runs-on: [self-hosted, linux, ARM64]
    defaults:
      run:
        working-directory: ros/humble/ubuntu/jammy
    steps:
      - uses: actions/checkout@v4

      - name: Install QEMU static binaries
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          endpoint: default
          append: |
            - node: hq0-builder-tegra
              platforms: linux/arm64

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}

      - name: Build and push
        uses: docker/bake-action@v4
        with:
          workdir: ros/humble/ubuntu/jammy
          push: ${{ github.event_name != 'pull_request' }}
