name: stereolabs-zedbot-4.X-l4t

on:
  push:
    branches: [ main ]
    paths:
      - 'stereolabs/zedbot/4.X/l4t/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'stereolabs/zedbot/4.X/l4t/**'
  workflow_dispatch:
jobs:
  build:
    runs-on: [self-hosted, linux, ARM64]
    defaults:
      run:
        working-directory: stereolabs/zedbot/4.X/l4t
    steps:
      - uses: actions/checkout@v4

      - name: Check the Containerfile with hadolint
        run: |
          $(git rev-parse --show-toplevel)/bin/lint.sh

      - name: Install QEMU static binaries
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build locally for testing
        uses: docker/bake-action@v4
        with:
          workdir: stereolabs/zedbot/4.X/l4t
          load: true

      - name: Run tests
        run: |
          tags=$(docker buildx bake --print | jq -r '.target[] | .tags[0]')
          for tag in $tags; do
            echo "$tag"
          done

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}

      - name: Build and push
        uses: docker/bake-action@v4
        with:
          workdir: stereolabs/zedbot/4.X/l4t
          push: ${{ github.event_name != 'pull_request' }}
